### ISSUE TITLE
CEH v12 virtual machines

### ISSUE THREAD

**Issue by ManualFTTH** [sufyandaredevil/EHRSRC_ZTM#1]
Hii!! Nice to meet you. I have been looking for the virtual machines to carry out the CEH v12 Practical laboratories, and I have not found them, do you have them by chance?

**Comment by sufyandaredevil** [comment]
> Hii!! Nice to meet you. I have been looking for the virtual machines to carry out the CEH v12 Practical laboratories, and I have not found them, do you have them by chance?

Hi @ManualFTTH, actually I haven't yet started going through the practical labs yet, also I guess you know already that those practical labs are not in the form of a virtual machine and can only be accessed online if you've paid for CEH practical. Or were you asking the VMs shown in the EC-Council CodeRed videos?

**Comment by ManualFTTH** [comment]
I mean the VMs prepared for the labs.

**Comment by sufyandaredevil** [comment]
> I mean the VMs prepared for the labs.

@ManualFTTH Like I said already CEH practical labs are not in the form of VMs and you can only find alternatives of those in websites like [vulnhub](https://www.vulnhub.com/) or goto [hackthebox](https://www.hackthebox.com) where you download a vulnerable VM, set it up locally or in case of hackthebox setup the VPN connection and start working on it
